// Seed Categories and Products Data for EasyCart
export const categoriesData = [
  {
    name: 'Electronics',
    slug: 'electronics',
    description: 'Smartphones, audio, smart watches, and home entertainment.',
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=800&q=80',
    isActive: true,
  },
  {
    name: 'Fashion & Apparel',
    slug: 'fashion',
    description: 'Trendy t-shirts, shirts, denim jeans, and designer ethnic wear.',
    image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800&q=80',
    isActive: true,
  },
  {
    name: 'Footwear',
    slug: 'footwear',
    description: 'Running shoes, casual sneakers, formal loafers, and comfort footwear.',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80',
    isActive: true,
  },
  {
    name: 'Home & Kitchen',
    slug: 'home-kitchen',
    description: 'Cookware, bath essentials, modern home decor, and smart appliances.',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&q=80',
    isActive: true,
  },
  {
    name: 'Sports & Fitness',
    slug: 'sports',
    description: 'Gym equipment, yoga gear, training accessories, and hydration flasks.',
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&q=80',
    isActive: true,
  },
  {
    name: 'Beauty & Grooming',
    slug: 'beauty',
    description: 'Skin care serums, organic hair oils, perfumes, and bath essentials.',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80',
    isActive: true,
  },
  {
    name: 'Accessories',
    slug: 'accessories',
    description: 'Leather wallets, UV aviator sunglasses, backpacks, and wrist watches.',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
    isActive: true,
  },
];

export const getProductsData = (catMap) => [
  // ================= ELECTRONICS (5 Products) =================
  {
    name: 'AudioTech Pro Wireless ANC Headphones',
    slug: 'audiotech-pro-wireless-anc-headphones',
    description: 'Experience studio-quality sound with hybrid Active Noise Cancellation, 40 hours of playtime, ultra-comfortable memory foam ear cushions, and transparency audio mode.',
    shortDescription: 'Hybrid ANC wireless over-ear headphones with 40h battery.',
    category: catMap['electronics'],
    brandName: 'AudioTech',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&q=80',
    ],
    variants: [
      { variantId: 'at-wh-01', sku: 'AT-WH-BLK', color: 'Midnight Black', price: 4999, discountPrice: 3499, stock: 45, images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80'], isActive: true },
      { variantId: 'at-wh-02', sku: 'AT-WH-SLV', color: 'Lunar Silver', price: 4999, discountPrice: 3499, stock: 30, images: ['https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Driver Size', value: '40mm Neodymium' },
      { name: 'Battery Life', value: 'Up to 40 Hours' },
      { name: 'Connectivity', value: 'Bluetooth 5.3 + 3.5mm AUX' },
    ],
    tags: ['headphones', 'wireless', 'anc', 'audio', 'electronics'],
    rating: 4.8,
    numReviews: 42,
    soldCount: 156,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'ChronoMax Series 7 AMOLED Smartwatch',
    slug: 'chronomax-series-7-amoled-smartwatch',
    description: 'Stay connected with a vibrant 1.43-inch AMOLED display, BT calling, 120+ sports modes, 24/7 heart rate & SpO2 monitoring, and IP68 water resistance.',
    shortDescription: '1.43" AMOLED Smartwatch with Bluetooth Calling & SpO2.',
    category: catMap['electronics'],
    brandName: 'ChronoMax',
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
    ],
    variants: [
      { variantId: 'cm-sw-01', sku: 'CM-SW-BLK', color: 'Obsidian Black', price: 4499, discountPrice: 2799, stock: 40, images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80'], isActive: true },
      { variantId: 'cm-sw-02', sku: 'CM-SW-SLV', color: 'Silver Chrome', price: 4499, discountPrice: 2799, stock: 25, images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Display', value: '1.43" AMOLED Always-On' },
      { name: 'Battery Life', value: 'Up to 7 Days' },
      { name: 'Water Resistance', value: 'IP68 Certified' },
    ],
    tags: ['smartwatch', 'wearable', 'fitness', 'electronics'],
    rating: 4.5,
    numReviews: 32,
    soldCount: 98,
    isFeatured: true,
    isNewArrival: true,
  },
  {
    name: 'SoundPulse Splash 20W Rugged Bluetooth Speaker',
    slug: 'soundpulse-splash-20w-bluetooth-speaker',
    description: 'Compact powerhouse delivers 360-degree room-filling sound with deep bass radiators. IPX7 waterproof rating, 24 hours of playtime, and stereo pairing support.',
    shortDescription: '20W IPX7 waterproof outdoor Bluetooth speaker with deep bass.',
    category: catMap['electronics'],
    brandName: 'SoundPulse',
    images: [
      'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80',
    ],
    variants: [
      { variantId: 'sp-spk-01', sku: 'SP-SPK-BLK', color: 'Midnight Black', price: 2999, discountPrice: 1699, stock: 35, images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80'], isActive: true },
      { variantId: 'sp-spk-02', sku: 'SP-SPK-BLU', color: 'Ocean Blue', price: 2999, discountPrice: 1699, stock: 20, images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Audio Output', value: '20W RMS Dual Drivers' },
      { name: 'Waterproof Rating', value: 'IPX7 Submersible' },
    ],
    tags: ['speaker', 'bluetooth', 'audio', 'waterproof', 'electronics'],
    rating: 4.7,
    numReviews: 45,
    soldCount: 190,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'PowerDrive 65W GaN Dual USB-C Fast Charger',
    slug: 'powerdrive-65w-gan-dual-usbc-charger',
    description: 'Advanced Gallium Nitride (GaN III) technology delivers ultra-compact fast charging for laptops, tablets, and phones simultaneously.',
    shortDescription: 'Compact 65W GaN charger with Dual USB-C & USB-A ports.',
    category: catMap['electronics'],
    brandName: 'PowerDrive',
    images: [
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80',
    ],
    variants: [
      { variantId: 'pd-ch-01', sku: 'PD-65W-WHT', color: 'Polar White', price: 2499, discountPrice: 1499, stock: 60, images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Power Output', value: '65W Max Power Delivery 3.0' },
      { name: 'Ports', value: '2x USB-C + 1x USB-A' },
    ],
    tags: ['charger', 'adapter', 'fast charge', 'electronics'],
    rating: 4.8,
    numReviews: 39,
    soldCount: 140,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'ProVision Ultra HD 4K Smart TV 55 Inch',
    slug: 'provision-ultra-hd-4k-smart-tv-55-inch',
    description: 'Vibrant Dolby Vision HDR10+ display with MEMC motion smoothing, quad-core processor, Dolby Atmos 30W stereo speakers, and hands-free Google Voice assistance.',
    shortDescription: '55" Ultra HD 4K Smart TV with Dolby Vision & Atmos.',
    category: catMap['electronics'],
    brandName: 'ProVision',
    images: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&q=80',
    ],
    variants: [
      { variantId: 'pv-tv-55', sku: 'PV-TV-55-UHD', size: '55 Inch', price: 44999, discountPrice: 32999, stock: 12, images: ['https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Resolution', value: '4K Ultra HD (3840 x 2160)' },
      { name: 'Refresh Rate', value: '60 Hz with MEMC' },
    ],
    tags: ['tv', 'television', 'smart tv', 'electronics', '4k'],
    rating: 4.7,
    numReviews: 45,
    soldCount: 88,
    isFeatured: true,
    isBestSeller: true,
  },

  // ================= FASHION & APPAREL (5 Products) =================
  {
    name: 'StyleCo 100% Combed Cotton Casual T-Shirt',
    slug: 'styleco-combed-cotton-casual-tshirt',
    description: 'Crafted from 180 GSM bio-washed 100% combed cotton, this crewneck t-shirt offers a tailored breathable fit that stays soft wash after wash.',
    shortDescription: 'Classic crew-neck premium cotton everyday t-shirt.',
    category: catMap['fashion'],
    brandName: 'StyleCo',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80',
    ],
    variants: [
      { variantId: 'sc-ts-01', sku: 'SC-TS-BLK-M', color: 'Jet Black', size: 'M', price: 999, discountPrice: 599, stock: 60, images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80'], isActive: true },
      { variantId: 'sc-ts-02', sku: 'SC-TS-BLK-L', color: 'Jet Black', size: 'L', price: 999, discountPrice: 599, stock: 55, images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80'], isActive: true },
      { variantId: 'sc-ts-03', sku: 'SC-TS-NAV-M', color: 'Navy Blue', size: 'M', price: 999, discountPrice: 599, stock: 40, images: ['https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Material', value: '100% Bio-washed Cotton' },
      { name: 'Fit', value: 'Regular Fit' },
    ],
    tags: ['tshirt', 'cotton', 'men', 'fashion', 'casual'],
    rating: 4.6,
    numReviews: 88,
    soldCount: 340,
    isFeatured: true,
    isNewArrival: true,
  },
  {
    name: 'UrbanClassic Slim Fit Stretch Denim Jeans',
    slug: 'urbanclassic-slim-fit-stretch-denim-jeans',
    description: 'Modern 5-pocket denim jeans tailored from premium 98% cotton and 2% elastane for unrestricted movement and durable daily comfort.',
    shortDescription: 'Premium stretchable slim fit casual denim jeans.',
    category: catMap['fashion'],
    brandName: 'UrbanClassic',
    images: [
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&q=80',
    ],
    variants: [
      { variantId: 'uc-jn-01', sku: 'UC-JN-IND-32', color: 'Dark Indigo', size: '32', price: 2499, discountPrice: 1499, stock: 40, images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&q=80'], isActive: true },
      { variantId: 'uc-jn-02', sku: 'UC-JN-BLK-32', color: 'Washed Black', size: '32', price: 2499, discountPrice: 1499, stock: 35, images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Fabric', value: '98% Cotton, 2% Elastane' },
      { name: 'Rise', value: 'Mid-Rise' },
    ],
    tags: ['jeans', 'denim', 'pants', 'fashion', 'men'],
    rating: 4.5,
    numReviews: 76,
    soldCount: 280,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Elegance Art Silk Woven Banarasi Saree',
    slug: 'elegance-art-silk-woven-banarasi-saree',
    description: 'Traditional festive Banarasi woven motif saree in rich zari embroidery with an unstitched matching blouse piece.',
    shortDescription: 'Festive Banarasi zari woven art silk saree with blouse.',
    category: catMap['fashion'],
    brandName: 'Elegance',
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&q=80',
    ],
    variants: [
      { variantId: 'el-sr-01', sku: 'EL-SR-RED', color: 'Royal Crimson', price: 3499, discountPrice: 1699, stock: 25, images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&q=80'], isActive: true },
      { variantId: 'el-sr-02', sku: 'EL-SR-GRN', color: 'Emerald Green', price: 3499, discountPrice: 1699, stock: 15, images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Fabric', value: 'Art Silk with Jacquard Zari' },
      { name: 'Length', value: '5.5m Saree + 0.8m Blouse Piece' },
    ],
    tags: ['saree', 'ethnic', 'traditional', 'fashion', 'women'],
    rating: 4.8,
    numReviews: 53,
    soldCount: 145,
    isFeatured: false,
    isNewArrival: true,
  },
  {
    name: 'Horizon Pure Linen Casual Button-Down Shirt',
    slug: 'horizon-pure-linen-casual-shirt',
    description: 'Lightweight, pre-washed 100% French linen long-sleeve shirt with a relaxed cut and classic mandarin collar for warm summer outings.',
    shortDescription: '100% pure linen casual shirt with mandarin collar.',
    category: catMap['fashion'],
    brandName: 'Horizon',
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80',
    ],
    variants: [
      { variantId: 'hz-sh-01', sku: 'HZ-SH-SKY-M', color: 'Sky Blue', size: 'M', price: 2199, discountPrice: 1399, stock: 30, images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80'], isActive: true },
      { variantId: 'hz-sh-02', sku: 'HZ-SH-WHT-L', color: 'Ivory White', size: 'L', price: 2199, discountPrice: 1399, stock: 25, images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Fabric', value: '100% French Linen' },
      { name: 'Fit', value: 'Relaxed Regular Fit' },
    ],
    tags: ['shirt', 'linen', 'men', 'fashion', 'summer'],
    rating: 4.7,
    numReviews: 38,
    soldCount: 120,
    isFeatured: true,
    isNewArrival: false,
  },
  {
    name: 'Aura Floral Bohemian Chiffon Summer Dress',
    slug: 'aura-floral-bohemian-chiffon-summer-dress',
    description: 'Breezy layered chiffon dress with floral botanical print, sweetheart neckline, tiered ruffle hem, and breathable cotton inner lining.',
    shortDescription: 'Floral print tiered ruffle chiffon summer midi dress.',
    category: catMap['fashion'],
    brandName: 'Aura',
    images: [
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&q=80',
    ],
    variants: [
      { variantId: 'au-dr-01', sku: 'AU-DR-YLW-S', color: 'Sunset Coral', size: 'S', price: 2499, discountPrice: 1599, stock: 20, images: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&q=80'], isActive: true },
      { variantId: 'au-dr-02', sku: 'AU-DR-YLW-M', color: 'Sunset Coral', size: 'M', price: 2499, discountPrice: 1599, stock: 25, images: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Material', value: 'Georgette Chiffon with Cotton Lining' },
      { name: 'Length', value: 'Midi Dress (42 inches)' },
    ],
    tags: ['dress', 'summer', 'floral', 'women', 'fashion'],
    rating: 4.6,
    numReviews: 29,
    soldCount: 110,
    isFeatured: false,
    isNewArrival: true,
  },

  // ================= FOOTWEAR (5 Products) =================
  {
    name: 'AeroStride Prime Breathable Running Shoes',
    slug: 'aerostride-prime-breathable-running-shoes',
    description: 'Engineered for athletes and daily fitness enthusiasts. Features responsive foam cushioning, high-traction rubber outsole, and lightweight breathable mesh upper.',
    shortDescription: 'Lightweight cushioned performance athletic running shoes.',
    category: catMap['footwear'],
    brandName: 'AeroStride',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80',
    ],
    variants: [
      { variantId: 'as-sh-01', sku: 'AS-RED-8', color: 'Crimson Red', size: 'UK 8', price: 3499, discountPrice: 2299, stock: 25, images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80'], isActive: true },
      { variantId: 'as-sh-02', sku: 'AS-RED-9', color: 'Crimson Red', size: 'UK 9', price: 3499, discountPrice: 2299, stock: 20, images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80'], isActive: true },
      { variantId: 'as-sh-03', sku: 'AS-WHT-8', color: 'Pure White', size: 'UK 8', price: 3499, discountPrice: 2299, stock: 18, images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Sole Material', value: 'High Abrasion Rubber' },
      { name: 'Upper Material', value: 'Engineered Knit Mesh' },
    ],
    tags: ['shoes', 'running', 'footwear', 'sports'],
    rating: 4.7,
    numReviews: 64,
    soldCount: 215,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'RetroGlide Urban Low-Top Canvas Sneakers',
    slug: 'retroglide-urban-lowtop-canvas-sneakers',
    description: 'Timeless silhouette reimagined with vulcanized rubber soles, breathable canvas lining, and ortholite footbeds for maximum casual comfort.',
    shortDescription: 'Classic low-top vulcanized casual canvas sneakers.',
    category: catMap['footwear'],
    brandName: 'RetroGlide',
    images: [
      'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&q=80',
    ],
    variants: [
      { variantId: 'rg-sn-01', sku: 'RG-WHT-8', color: 'Off White', size: 'UK 8', price: 2199, discountPrice: 1299, stock: 25, images: ['https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&q=80'], isActive: true },
      { variantId: 'rg-sn-02', sku: 'RG-BLK-8', color: 'Pitch Black', size: 'UK 8', price: 2199, discountPrice: 1299, stock: 30, images: ['https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Sole Material', value: 'Vulcanized Gum Rubber' },
      { name: 'Upper', value: '12 oz Heavyweight Canvas' },
    ],
    tags: ['sneakers', 'footwear', 'casual', 'shoes'],
    rating: 4.6,
    numReviews: 48,
    soldCount: 175,
    isFeatured: true,
    isNewArrival: true,
  },
  {
    name: 'OxfordCraft Handcrafted Genuine Leather Loafers',
    slug: 'oxfordcraft-genuine-leather-loafers',
    description: 'Artisan handcrafted penny loafers made from full-grain bovine leather with cushioned leather insole and anti-skid TPR sole.',
    shortDescription: 'Handcrafted formal full-grain leather penny loafers.',
    category: catMap['footwear'],
    brandName: 'OxfordCraft',
    images: [
      'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&q=80',
    ],
    variants: [
      { variantId: 'oc-lf-01', sku: 'OC-LF-TAN-8', color: 'Rich Tan', size: 'UK 8', price: 3999, discountPrice: 2499, stock: 20, images: ['https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&q=80'], isActive: true },
      { variantId: 'oc-lf-02', sku: 'OC-LF-BLK-9', color: 'Classic Black', size: 'UK 9', price: 3999, discountPrice: 2499, stock: 15, images: ['https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Upper Material', value: 'Full-Grain Bovine Leather' },
      { name: 'Insole', value: 'High Density Memory Cushion' },
    ],
    tags: ['formal', 'loafers', 'leather', 'shoes', 'footwear'],
    rating: 4.8,
    numReviews: 35,
    soldCount: 95,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'TrailBlazer Waterproof Trekking Hiking Boots',
    slug: 'trailblazer-waterproof-hiking-boots',
    description: 'All-terrain hiking boots with HydroGuard waterproof membrane, reinforced rubber toe cap, and multi-directional lugged Vibram-style sole.',
    shortDescription: 'All-weather waterproof ankle-support hiking boots.',
    category: catMap['footwear'],
    brandName: 'TrailBlazer',
    images: [
      'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=800&q=80',
    ],
    variants: [
      { variantId: 'tb-hb-01', sku: 'TB-HB-OLV-8', color: 'Forest Olive', size: 'UK 8', price: 4799, discountPrice: 3199, stock: 18, images: ['https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=800&q=80'], isActive: true },
      { variantId: 'tb-hb-02', sku: 'TB-HB-BRN-9', color: 'Earth Brown', size: 'UK 9', price: 4799, discountPrice: 3199, stock: 14, images: ['https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Waterproofing', value: 'HydroGuard Breathable Membrane' },
      { name: 'Sole', value: 'Deep Lug Multi-Directional Grip' },
    ],
    tags: ['boots', 'hiking', 'trekking', 'waterproof', 'footwear'],
    rating: 4.9,
    numReviews: 41,
    soldCount: 82,
    isFeatured: false,
    isNewArrival: true,
  },
  {
    name: 'CloudStride Ultra-Soft Dual Density Flip-Flops',
    slug: 'cloudstride-ultrasoft-comfort-flipflops',
    description: 'Ergonomic orthopedic comfort slippers with dual-density EVA foam, anti-sweat textured footbed, and soft microfiber toe post.',
    shortDescription: 'Orthopedic dual-density ultra-soft daily flip-flops.',
    category: catMap['footwear'],
    brandName: 'CloudStride',
    images: [
      'https://images.unsplash.com/photo-1595341888016-a392ef81b7de?w=800&q=80',
    ],
    variants: [
      { variantId: 'cs-ff-01', sku: 'CS-FF-NVY-8', color: 'Navy Blue', size: 'UK 8', price: 799, discountPrice: 449, stock: 50, images: ['https://images.unsplash.com/photo-1595341888016-a392ef81b7de?w=800&q=80'], isActive: true },
      { variantId: 'cs-ff-02', sku: 'CS-FF-BLK-9', color: 'Stealth Black', size: 'UK 9', price: 799, discountPrice: 449, stock: 45, images: ['https://images.unsplash.com/photo-1595341888016-a392ef81b7de?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Material', value: 'Dual-Density Lightweight EVA' },
      { name: 'Heel Support', value: 'Cupped Arch Support Footbed' },
    ],
    tags: ['slippers', 'flipflops', 'comfort', 'footwear', 'casual'],
    rating: 4.5,
    numReviews: 62,
    soldCount: 310,
    isFeatured: false,
    isBestSeller: true,
  },

  // ================= HOME & KITCHEN (5 Products) =================
  {
    name: 'CulinaryPro Non-Stick Granite Cookware 3-Piece Set',
    slug: 'culinarypro-non-stick-granite-cookware-set',
    description: 'Induction and gas friendly 5-layer German granite coating with stay-cool handles. Set includes 24cm Frying Pan, 28cm Kadhai with Glass Lid, and 24cm Flat Tawa.',
    shortDescription: 'German granite coating 3-piece induction cookware set.',
    category: catMap['home-kitchen'],
    brandName: 'CulinaryPro',
    images: [
      'https://images.unsplash.com/photo-1584990347449-32d8ff551f38?w=800&q=80',
    ],
    variants: [
      { variantId: 'cp-cw-01', sku: 'CP-CW-BLK', color: 'Granite Black', price: 3999, discountPrice: 2499, stock: 20, images: ['https://images.unsplash.com/photo-1584990347449-32d8ff551f38?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Coating', value: '5-Layer PFOA Free Granite' },
      { name: 'Base Type', value: 'Gas and Induction Compatible' },
    ],
    tags: ['cookware', 'kitchen', 'non-stick', 'home'],
    rating: 4.8,
    numReviews: 29,
    soldCount: 82,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'LuxSoft Egyptian Cotton 600 GSM Bath Towel 4-Piece Set',
    slug: 'luxsoft-egyptian-cotton-bath-towel-set',
    description: 'Plush, ultra-absorbent 600 GSM long-staple Egyptian cotton towels. Features zero-twist yarn for cloud-like softness that dries quickly.',
    shortDescription: '600 GSM long-staple Egyptian cotton plush bath towels.',
    category: catMap['home-kitchen'],
    brandName: 'LuxSoft',
    images: [
      'https://images.unsplash.com/photo-1616627547584-bf28cee262db?w=800&q=80',
    ],
    variants: [
      { variantId: 'ls-tw-01', sku: 'LS-TW-GRY', color: 'Charcoal Grey', price: 2299, discountPrice: 1399, stock: 35, images: ['https://images.unsplash.com/photo-1616627547584-bf28cee262db?w=800&q=80'], isActive: true },
      { variantId: 'ls-tw-02', sku: 'LS-TW-WHT', color: 'Arctic White', price: 2299, discountPrice: 1399, stock: 25, images: ['https://images.unsplash.com/photo-1616627547584-bf28cee262db?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'GSM', value: '600 GSM Heavyweight' },
      { name: 'Material', value: '100% Ring-Spun Egyptian Cotton' },
    ],
    tags: ['towels', 'bath', 'cotton', 'home'],
    rating: 4.7,
    numReviews: 52,
    soldCount: 165,
    isFeatured: false,
    isNewArrival: false,
  },
  {
    name: 'LuminaTouch Dimmable LED Desk Lamp with Wireless Pad',
    slug: 'luminatouch-dimmable-led-desk-lamp',
    description: 'Sleek architectural LED study lamp with 5 color temperatures, 6 brightness sliders, 10W wireless charging base, and 45-minute auto sleep timer.',
    shortDescription: 'Flicker-free eye-care LED lamp with 10W wireless charging base.',
    category: catMap['home-kitchen'],
    brandName: 'LuminaTouch',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80',
    ],
    variants: [
      { variantId: 'lt-lp-01', sku: 'LT-LP-WHT', color: 'Arctic White', price: 2999, discountPrice: 1799, stock: 25, images: ['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80'], isActive: true },
      { variantId: 'lt-lp-02', sku: 'LT-LP-GRY', color: 'Space Grey', price: 2999, discountPrice: 1799, stock: 20, images: ['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Brightness', value: 'Up to 800 Lumens' },
      { name: 'Wireless Charging', value: '10W Qi-Certified Fast Pad' },
    ],
    tags: ['lamp', 'lighting', 'desk', 'home', 'study'],
    rating: 4.8,
    numReviews: 31,
    soldCount: 95,
    isFeatured: false,
    isNewArrival: true,
  },
  {
    name: 'AromaMist Ultrasonic 500ml Essential Oil Diffuser',
    slug: 'aromamist-ultrasonic-essential-oil-diffuser',
    description: 'Whisper-quiet 500ml ultrasonic cool mist aroma humidifier with 7 ambient LED mood lighting colors and auto waterless shut-off protection.',
    shortDescription: '500ml ultrasonic cool mist aroma diffuser with 7 LED colors.',
    category: catMap['home-kitchen'],
    brandName: 'AromaMist',
    images: [
      'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&q=80',
    ],
    variants: [
      { variantId: 'am-df-01', sku: 'AM-DF-WOOD', color: 'Natural Wood Grain', price: 1899, discountPrice: 1199, stock: 35, images: ['https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Tank Capacity', value: '500 ml' },
      { name: 'Working Time', value: 'Up to 12 Hours Continuous' },
    ],
    tags: ['diffuser', 'aromatherapy', 'home', 'fragrance'],
    rating: 4.7,
    numReviews: 44,
    soldCount: 130,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'ChefMaster Pre-Seasoned Cast Iron Dutch Oven 5-Quart',
    slug: 'chefmaster-cast-iron-dutch-oven-5qt',
    description: 'Heavyweight enamel cast iron Dutch oven with self-basting lid condensation nodules. Excellent heat retention for slow cooking, braising, and sourdough bread baking.',
    shortDescription: '5-Quart enameled heavy cast iron Dutch oven with lid.',
    category: catMap['home-kitchen'],
    brandName: 'ChefMaster',
    images: [
      'https://images.unsplash.com/photo-1544233726-9f1d2b27be8b?w=800&q=80',
    ],
    variants: [
      { variantId: 'cm-do-01', sku: 'CM-DO-RED-5Q', color: 'Cherry Red', size: '5 Quart', price: 4999, discountPrice: 3299, stock: 15, images: ['https://images.unsplash.com/photo-1544233726-9f1d2b27be8b?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Material', value: 'Enameled Cast Iron' },
      { name: 'Oven Safe', value: 'Up to 500°F (260°C)' },
    ],
    tags: ['dutch oven', 'cast iron', 'cookware', 'baking', 'home'],
    rating: 4.9,
    numReviews: 33,
    soldCount: 75,
    isFeatured: true,
    isBestSeller: false,
  },

  // ================= SPORTS & FITNESS (5 Products) =================
  {
    name: 'FlexFit Anti-Tear Dual Color Yoga Mat 6mm',
    slug: 'flexfit-anti-tear-yoga-mat-6mm',
    description: 'Eco-friendly TPE material with double-sided anti-slip texture, laser alignment guide lines, and complimentary carrying strap.',
    shortDescription: 'High density anti-slip 6mm TPE exercise & yoga mat.',
    category: catMap['sports'],
    brandName: 'FlexFit',
    images: [
      'https://images.unsplash.com/photo-1592432678016-e910b452f9a2?w=800&q=80',
    ],
    variants: [
      { variantId: 'ff-ym-01', sku: 'FF-YM-TEAL', color: 'Teal & Grey', price: 1799, discountPrice: 999, stock: 50, images: ['https://images.unsplash.com/photo-1592432678016-e910b452f9a2?w=800&q=80'], isActive: true },
      { variantId: 'ff-ym-02', sku: 'FF-YM-PNK', color: 'Berry Pink', price: 1799, discountPrice: 999, stock: 35, images: ['https://images.unsplash.com/photo-1592432678016-e910b452f9a2?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Thickness', value: '6 mm High-Density' },
      { name: 'Material', value: 'Non-Toxic Eco TPE' },
    ],
    tags: ['yoga', 'fitness', 'exercise', 'mat', 'sports'],
    rating: 4.6,
    numReviews: 54,
    soldCount: 160,
    isFeatured: false,
    isNewArrival: true,
  },
  {
    name: 'IronCore 20KG Adjustable Vinyl Dumbbell Weight Set',
    slug: 'ironcore-20kg-adjustable-dumbbell-set',
    description: 'Versatile home workout system with interchangeable vinyl weight plates, steel connector bar to convert into a barbell, and non-slip safety spinlock collars.',
    shortDescription: '20KG 2-in-1 adjustable dumbbell and barbell strength set.',
    category: catMap['sports'],
    brandName: 'IronCore',
    images: [
      'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&q=80',
    ],
    variants: [
      { variantId: 'ic-db-01', sku: 'IC-DB-20', size: '20 KG Set', price: 3499, discountPrice: 1999, stock: 20, images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Total Weight', value: '20 Kilograms' },
      { name: 'Configuration', value: 'Convertible Dumbbell & Barbell' },
    ],
    tags: ['weights', 'dumbbells', 'fitness', 'gym', 'sports'],
    rating: 4.6,
    numReviews: 38,
    soldCount: 115,
    isFeatured: false,
    isNewArrival: false,
  },
  {
    name: 'HydroFlask Vacuum Insulated Stainless Steel Bottle 1000ml',
    slug: 'hydroflask-vacuum-insulated-water-bottle-1000ml',
    description: 'Double-wall TempShield insulation keeps beverages ice cold for up to 24 hours or piping hot for 12 hours. 100% leakproof flex cap with durable powder coat finish.',
    shortDescription: '1000ml double-wall vacuum insulated stainless steel bottle.',
    category: catMap['sports'],
    brandName: 'HydroFlask',
    images: [
      'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80',
    ],
    variants: [
      { variantId: 'hf-bt-01', sku: 'HF-1L-BLK', color: 'Midnight Matte', price: 1699, discountPrice: 999, stock: 55, images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80'], isActive: true },
      { variantId: 'hf-bt-02', sku: 'HF-1L-GRN', color: 'Olive Green', price: 1699, discountPrice: 999, stock: 40, images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Capacity', value: '1000 ml / 32 oz' },
      { name: 'Steel Grade', value: '18/8 Pro-Grade Stainless Steel' },
    ],
    tags: ['bottle', 'flask', 'sports', 'hydration', 'gym'],
    rating: 4.9,
    numReviews: 72,
    soldCount: 290,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'ProSpeed High-Speed Ball Bearing Weighted Jump Rope',
    slug: 'prospeed-weighted-jump-rope',
    description: 'Aerodynamic steel wire cable with 360-degree dual ball bearings for tangle-free ultra-fast rotation. Includes removable 150g handle weights for intense cardio.',
    shortDescription: 'Dual ball-bearing weighted steel wire speed jump rope.',
    category: catMap['sports'],
    brandName: 'ProSpeed',
    images: [
      'https://images.unsplash.com/photo-1598971861713-54ad16a7e72e?w=800&q=80',
    ],
    variants: [
      { variantId: 'ps-jr-01', sku: 'PS-JR-BLK', color: 'Stealth Black', price: 999, discountPrice: 499, stock: 65, images: ['https://images.unsplash.com/photo-1598971861713-54ad16a7e72e?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Cable Length', value: '10ft Fully Adjustable Steel Wire' },
      { name: 'Bearings', value: '360° Industrial Steel Ball Bearings' },
    ],
    tags: ['jump rope', 'skipping', 'cardio', 'fitness', 'sports'],
    rating: 4.7,
    numReviews: 47,
    soldCount: 220,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'PowerLoop Fabric Heavy Resistance Bands Set of 3',
    slug: 'powerloop-fabric-resistance-bands-set',
    description: 'Thick non-slip fabric booty bands that won’t roll or pinch during squats or hip thrusts. 3 progressive resistance tiers: Light, Medium, and Heavy.',
    shortDescription: 'Anti-slip fabric resistance loop exercise bands 3-pack.',
    category: catMap['sports'],
    brandName: 'PowerLoop',
    images: [
      'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80',
    ],
    variants: [
      { variantId: 'pl-rb-01', sku: 'PL-RB-TRIO', color: 'Pastel Trio', price: 1299, discountPrice: 699, stock: 45, images: ['https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Material', value: 'Reinforced Cotton Elastic Blend' },
      { name: 'Levels', value: 'Light (15-25 lbs), Med (25-35 lbs), Heavy (35-50 lbs)' },
    ],
    tags: ['resistance bands', 'workout', 'fitness', 'sports'],
    rating: 4.8,
    numReviews: 51,
    soldCount: 195,
    isFeatured: false,
    isNewArrival: true,
  },

  // ================= BEAUTY & GROOMING (5 Products) =================
  {
    name: 'PureGlow 20% Vitamin C Radiance Face Serum',
    slug: 'pureglow-20-vitamin-c-radiance-face-serum',
    description: 'Formulated with stabilized 20% Ethyl Ascorbic Acid, Hyaluronic Acid, and Ferulic Acid. Brightens skin tone, reduces dark spots, and boosts collagen synthesis.',
    shortDescription: 'Advanced brightening antioxidant serum with Hyaluronic Acid.',
    category: catMap['beauty'],
    brandName: 'PureGlow',
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80',
    ],
    variants: [
      { variantId: 'pg-sr-01', sku: 'PG-VC-30', size: '30 ml', price: 899, discountPrice: 499, stock: 75, images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Key Ingredients', value: '20% Vitamin C, Ferulic Acid, Hyaluronic Acid' },
      { name: 'Skin Type', value: 'All Skin Types, Dermatologically Tested' },
    ],
    tags: ['serum', 'skincare', 'beauty', 'vitamin c'],
    rating: 4.9,
    numReviews: 110,
    soldCount: 420,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'PureBotanics Cold-Pressed Organic Moroccan Argan Oil',
    slug: 'purebotanics-organic-moroccan-argan-oil',
    description: '100% pure USDA-certified virgin cold-pressed Argan oil. Deeply nourishes dry hair, tames stubborn frizz, and moisturizes facial cuticles.',
    shortDescription: '100% pure cold-pressed Moroccan argan oil for hair and face.',
    category: catMap['beauty'],
    brandName: 'PureBotanics',
    images: [
      'https://images.unsplash.com/photo-1608248597359-009139a06ba9?w=800&q=80',
    ],
    variants: [
      { variantId: 'pb-ao-01', sku: 'PB-AO-100', size: '100 ml', price: 1199, discountPrice: 699, stock: 50, images: ['https://images.unsplash.com/photo-1608248597359-009139a06ba9?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Certification', value: 'USDA Organic, Cruelty-Free' },
      { name: 'Extraction', value: 'Cold-Pressed Unrefined' },
    ],
    tags: ['hair oil', 'argan', 'beauty', 'organic'],
    rating: 4.8,
    numReviews: 61,
    soldCount: 230,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'GlowRitual Japanese Cherry Blossom Shower Gel 300ml',
    slug: 'glowritual-japanese-cherry-blossom-shower-gel',
    description: 'Indulge in a luxurious lather infused with natural Cherry Blossom extracts, Aloe Vera, and Shea Butter for 24-hour velvety soft hydration.',
    shortDescription: 'Gentle hydrating body wash with natural Cherry Blossom.',
    category: catMap['beauty'],
    brandName: 'GlowRitual',
    images: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80',
    ],
    variants: [
      { variantId: 'gr-sg-01', sku: 'GR-SG-300', size: '300 ml', price: 699, discountPrice: 399, stock: 65, images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Formulation', value: 'Sulfate-Free & Paraben-Free' },
      { name: 'Fragrance', value: 'Sweet Japanese Sakura Blossom' },
    ],
    tags: ['bodywash', 'beauty', 'bath', 'shower gel'],
    rating: 4.6,
    numReviews: 40,
    soldCount: 180,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'VelvetKiss Hydrating Matte Liquid Lip Tint',
    slug: 'velvetkiss-hydrating-matte-liquid-lip-tint',
    description: 'Weightless transfer-proof formula enriched with Vitamin E and Jojoba oil. Delivers 12 hours of rich matte color without drying lips.',
    shortDescription: 'Transfer-proof 12-hour matte liquid lipstick with Vitamin E.',
    category: catMap['beauty'],
    brandName: 'VelvetKiss',
    images: [
      'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80',
    ],
    variants: [
      { variantId: 'vk-lt-01', sku: 'VK-LT-ROSE', color: 'Ruby Rose', price: 699, discountPrice: 429, stock: 50, images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80'], isActive: true },
      { variantId: 'vk-lt-02', sku: 'VK-LT-NUDE', color: 'Nude Coral', price: 699, discountPrice: 429, stock: 45, images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Finish', value: 'Velvet Matte' },
      { name: 'Wear Time', value: 'Up to 12 Hours Transfer-Proof' },
    ],
    tags: ['lipstick', 'makeup', 'beauty', 'cosmetics'],
    rating: 4.7,
    numReviews: 55,
    soldCount: 260,
    isFeatured: true,
    isNewArrival: true,
  },
  {
    name: 'MineralEarth Detoxifying Dead Sea Clay Face Mask',
    slug: 'mineralearth-dead-sea-clay-face-mask',
    description: 'Pore-clearing natural mud mask infused with Dead Sea minerals, Activated Charcoal, and Tea Tree oil to absorb excess oil and unclog blackheads.',
    shortDescription: 'Dead Sea mineral clay mask for deep pore cleansing.',
    category: catMap['beauty'],
    brandName: 'MineralEarth',
    images: [
      'https://images.unsplash.com/photo-1567928815104-b7980ee5032e?w=800&q=80',
    ],
    variants: [
      { variantId: 'me-cm-01', sku: 'ME-CM-150G', size: '150g Jar', price: 799, discountPrice: 499, stock: 40, images: ['https://images.unsplash.com/photo-1567928815104-b7980ee5032e?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Key Ingredients', value: 'Dead Sea Mud, Activated Charcoal, Tea Tree Oil' },
      { name: 'Net Weight', value: '150 Grams' },
    ],
    tags: ['mask', 'skincare', 'charcoal', 'beauty'],
    rating: 4.8,
    numReviews: 36,
    soldCount: 140,
    isFeatured: false,
    isBestSeller: true,
  },

  // ================= ACCESSORIES (5 Products) =================
  {
    name: 'RegalCraft Genuine Top-Grain Leather RFID Bifold Wallet',
    slug: 'regalcraft-genuine-leather-rfid-bifold-wallet',
    description: 'Precision stitched from 100% genuine top-grain cowhide leather. Equipped with advanced RFID blocking lining to protect your cards against digital theft.',
    shortDescription: 'Slim RFID-blocking genuine leather bi-fold wallet.',
    category: catMap['accessories'],
    brandName: 'RegalCraft',
    images: [
      'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80',
    ],
    variants: [
      { variantId: 'rc-wl-01', sku: 'RC-WL-BRN', color: 'Vintage Brown', price: 1499, discountPrice: 899, stock: 60, images: ['https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80'], isActive: true },
      { variantId: 'rc-wl-02', sku: 'RC-WL-BLK', color: 'Jet Black', price: 1499, discountPrice: 899, stock: 45, images: ['https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Material', value: '100% Top-Grain Cowhide' },
      { name: 'Features', value: '8 Card Slots, 2 Currency Compartments, RFID Shield' },
    ],
    tags: ['wallet', 'leather', 'accessories', 'rfid', 'men'],
    rating: 4.8,
    numReviews: 68,
    soldCount: 290,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'NeoShield Polarized Metal Aviator Sunglasses',
    slug: 'neoshield-polarized-metal-aviator-sunglasses',
    description: 'Timeless teardrop pilot shape equipped with UV400 polarized lenses that eliminate harsh glare and protect eyesight in bright outdoor light.',
    shortDescription: 'UV400 polarized aviator sunglasses with spring hinges.',
    category: catMap['accessories'],
    brandName: 'NeoShield',
    images: [
      'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80',
    ],
    variants: [
      { variantId: 'ns-sg-01', sku: 'NS-GLD-GRN', color: 'Gold Frame / G-15 Green', price: 1999, discountPrice: 1099, stock: 35, images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80'], isActive: true },
      { variantId: 'ns-sg-02', sku: 'NS-GUN-GRY', color: 'Gunmetal / Polarized Grey', price: 1999, discountPrice: 1099, stock: 30, images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Lens Protection', value: 'UV400 Polarized Triacetate' },
      { name: 'Frame Material', value: 'Corrosion-Resistant Metal Alloy' },
    ],
    tags: ['sunglasses', 'aviators', 'accessories', 'eyewear'],
    rating: 4.7,
    numReviews: 44,
    soldCount: 135,
    isFeatured: false,
    isNewArrival: true,
  },
  {
    name: 'AeroPack Water-Resistant 15.6" Laptop Backpack',
    slug: 'aeropack-water-resistant-laptop-backpack',
    description: 'Modern commuter backpack with padded sleeve for up to 15.6-inch laptops, external USB charging pass-through, luggage strap, and water-repellent oxford fabric.',
    shortDescription: 'Sleek waterproof 15.6" laptop commuter backpack with USB port.',
    category: catMap['accessories'],
    brandName: 'AeroPack',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80',
    ],
    variants: [
      { variantId: 'ap-bp-01', sku: 'AP-BP-GRY', color: 'Heather Grey', price: 2899, discountPrice: 1699, stock: 40, images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80'], isActive: true },
      { variantId: 'ap-bp-02', sku: 'AP-BP-BLK', color: 'Stealth Black', price: 2899, discountPrice: 1699, stock: 35, images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Laptop Compartment', value: 'Dedicated Padded up to 15.6"' },
      { name: 'Capacity', value: '25 Liters' },
    ],
    tags: ['backpack', 'laptop bag', 'accessories', 'travel'],
    rating: 4.8,
    numReviews: 57,
    soldCount: 210,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'TitanHeritage Classic Chronograph Men\'s Watch',
    slug: 'titanheritage-classic-chronograph-watch',
    description: 'Elegantly styled stainless steel chronograph wrist watch with midnight blue sunray dial, tachymeter bezel, date display, and 50m water resistance.',
    shortDescription: 'Stainless steel analog chronograph watch with date window.',
    category: catMap['accessories'],
    brandName: 'TitanHeritage',
    images: [
      'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&q=80',
    ],
    variants: [
      { variantId: 'th-wt-01', sku: 'TH-WT-SLV', color: 'Silver & Blue Dial', price: 6499, discountPrice: 3899, stock: 25, images: ['https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&q=80'], isActive: true },
      { variantId: 'th-wt-02', sku: 'TH-WT-BLK', color: 'All-Black PVD', price: 6499, discountPrice: 3899, stock: 18, images: ['https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Movement', value: 'Japanese Quartz Chronograph' },
      { name: 'Case Diameter', value: '42 mm' },
      { name: 'Water Resistance', value: '5 ATM / 50 Meters' },
    ],
    tags: ['watch', 'analog', 'chronograph', 'accessories', 'men'],
    rating: 4.9,
    numReviews: 34,
    soldCount: 125,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'NomadCanvas Heavy-Duty Weekender Duffle Bag',
    slug: 'nomadcanvas-weekender-duffle-bag',
    description: 'Crafted from rugged 16 oz washed canvas with genuine leather trim. Features a separate ventilated shoe compartment, reinforced base studs, and detachable shoulder strap.',
    shortDescription: 'Rugged washed canvas weekender travel duffle with shoe compartment.',
    category: catMap['accessories'],
    brandName: 'NomadCanvas',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80',
    ],
    variants: [
      { variantId: 'nc-df-01', sku: 'NC-DF-KHK', color: 'Khaki Tan', price: 3299, discountPrice: 1999, stock: 25, images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80'], isActive: true },
      { variantId: 'nc-df-02', sku: 'NC-DF-GRN', color: 'Military Olive', price: 3299, discountPrice: 1999, stock: 20, images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80'], isActive: true },
    ],
    specifications: [
      { name: 'Capacity', value: '45 Liters' },
      { name: 'Shoe Pocket', value: 'Dedicated Side Zippered Pocket' },
    ],
    tags: ['duffle', 'travel', 'canvas', 'bag', 'accessories'],
    rating: 4.7,
    numReviews: 28,
    soldCount: 90,
    isFeatured: false,
    isNewArrival: true,
  },
];
